workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
        
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
    publishing:
      email:
        recipients:
          - your-email@example.com
