workflows:
  android-only:
    name: Android APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: دریافت وابستگی‌ها
        script: flutter pub get
      - name: ساخت APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
