workflows:
  android-only:
    name: Android APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - flutter create . --platforms android --overwrite
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
