name: video_editor
description: Video and photo editor app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  video_player: ^2.8.1
  chewie: ^1.7.0
  share_plus: ^7.2.1
  path_provider: ^2.1.0
  permission_handler: ^11.0.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
